
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridjal Fathoni
 */
public class Form_ATM extends javax.swing.JFrame {

    /**
     * Creates new form Form_ATM
     */
    public Form_ATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLanjut = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPIN = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bLanjut.setText("Lanjutkan");
        bLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLanjutActionPerformed(evt);
            }
        });
        getContentPane().add(bLanjut);
        bLanjut.setBounds(260, 90, 125, 33);

        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });
        getContentPane().add(bBatal);
        bBatal.setBounds(10, 90, 125, 33);

        jLabel1.setText("MASUKKAN 4 DIGIT PIN ANDA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 220, 32);

        jLabel2.setText("ATM BNI SYARIAH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 0, 140, 38);

        txtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPIN);
        txtPIN.setBounds(10, 50, 370, 30);

        setSize(new java.awt.Dimension(415, 171));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLanjutActionPerformed
        // TODO add your handling code here:
        int Pin;
       int pin=1234;
       
       Pin = Integer.parseInt(txtPIN.getText().toString());
       if (Pin == pin)
       {
           Transaksi a = new Transaksi();
           a.setVisible(true);
           dispose();
       }
       else if ( Pin != pin)
       {
           JOptionPane.showMessageDialog(null, "Masukkan PIN dengan benar!");
       }
       
    }//GEN-LAST:event_bLanjutActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
         System.exit(ABORT);
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bLanjut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPIN;
    // End of variables declaration//GEN-END:variables
}
